// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User_Gender int32

const (
	User_Male   User_Gender = 0
	User_Female User_Gender = 1
)

var User_Gender_name = map[int32]string{
	0: "Male",
	1: "Female",
}

var User_Gender_value = map[string]int32{
	"Male":   0,
	"Female": 1,
}

func (x User_Gender) String() string {
	return proto.EnumName(User_Gender_name, int32(x))
}

func (User_Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3, 0}
}

type GetUserReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserReq) Reset()         { *m = GetUserReq{} }
func (m *GetUserReq) String() string { return proto.CompactTextString(m) }
func (*GetUserReq) ProtoMessage()    {}
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *GetUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserReq.Unmarshal(m, b)
}
func (m *GetUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserReq.Marshal(b, m, deterministic)
}
func (m *GetUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserReq.Merge(m, src)
}
func (m *GetUserReq) XXX_Size() int {
	return xxx_messageInfo_GetUserReq.Size(m)
}
func (m *GetUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserReq proto.InternalMessageInfo

func (m *GetUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DelUserReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelUserReq) Reset()         { *m = DelUserReq{} }
func (m *DelUserReq) String() string { return proto.CompactTextString(m) }
func (*DelUserReq) ProtoMessage()    {}
func (*DelUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *DelUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelUserReq.Unmarshal(m, b)
}
func (m *DelUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelUserReq.Marshal(b, m, deterministic)
}
func (m *DelUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelUserReq.Merge(m, src)
}
func (m *DelUserReq) XXX_Size() int {
	return xxx_messageInfo_DelUserReq.Size(m)
}
func (m *DelUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelUserReq proto.InternalMessageInfo

func (m *DelUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CommonUserRes struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonUserRes) Reset()         { *m = CommonUserRes{} }
func (m *CommonUserRes) String() string { return proto.CompactTextString(m) }
func (*CommonUserRes) ProtoMessage()    {}
func (*CommonUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *CommonUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonUserRes.Unmarshal(m, b)
}
func (m *CommonUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonUserRes.Marshal(b, m, deterministic)
}
func (m *CommonUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonUserRes.Merge(m, src)
}
func (m *CommonUserRes) XXX_Size() int {
	return xxx_messageInfo_CommonUserRes.Size(m)
}
func (m *CommonUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_CommonUserRes proto.InternalMessageInfo

func (m *CommonUserRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CommonUserRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type User struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32       `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Hight                int32       `protobuf:"varint,3,opt,name=hight,proto3" json:"hight,omitempty"`
	Gender               User_Gender `protobuf:"varint,4,opt,name=gender,proto3,enum=user.User_Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetHight() int32 {
	if m != nil {
		return m.Hight
	}
	return 0
}

func (m *User) GetGender() User_Gender {
	if m != nil {
		return m.Gender
	}
	return User_Male
}

func init() {
	proto.RegisterEnum("user.User_Gender", User_Gender_name, User_Gender_value)
	proto.RegisterType((*GetUserReq)(nil), "user.GetUserReq")
	proto.RegisterType((*DelUserReq)(nil), "user.DelUserReq")
	proto.RegisterType((*CommonUserRes)(nil), "user.CommonUserRes")
	proto.RegisterType((*User)(nil), "user.User")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xbb, 0x36, 0x89, 0x3a, 0x12, 0xa9, 0xa3, 0x87, 0xd0, 0x83, 0x84, 0x9c, 0x2a, 0x48,
	0x84, 0x8a, 0xe0, 0xd5, 0x2a, 0xf6, 0xa4, 0x87, 0x15, 0x2f, 0xde, 0x62, 0x33, 0xa4, 0x85, 0x6e,
	0x56, 0x37, 0x51, 0xf0, 0x47, 0xf8, 0x37, 0xfc, 0x9d, 0x32, 0xb3, 0x81, 0x58, 0x50, 0x6f, 0x2f,
	0xbb, 0xdf, 0x7b, 0xd9, 0x79, 0x03, 0xf0, 0xd6, 0x90, 0xcb, 0x5f, 0x9c, 0x6d, 0x2d, 0x06, 0xac,
	0xb3, 0x14, 0x60, 0x4e, 0xed, 0x63, 0x43, 0x4e, 0xd3, 0x2b, 0x22, 0x04, 0x75, 0x61, 0x28, 0x51,
	0xa9, 0x9a, 0xec, 0x6a, 0xd1, 0x4c, 0xdc, 0xd0, 0xfa, 0x3f, 0xe2, 0x02, 0xe2, 0x6b, 0x6b, 0x8c,
	0xad, 0x3d, 0xd4, 0x30, 0xb4, 0xb0, 0xa5, 0x87, 0x42, 0x2d, 0x1a, 0x47, 0x30, 0x34, 0x4d, 0x95,
	0x6c, 0x89, 0x8f, 0x65, 0xf6, 0xa9, 0x20, 0x60, 0xc7, 0x6f, 0x99, 0x8c, 0x17, 0x15, 0x09, 0x1e,
	0x6a, 0x96, 0x78, 0x04, 0xe1, 0x72, 0x55, 0x2d, 0xdb, 0x64, 0x28, 0x67, 0xfe, 0x03, 0x4f, 0x20,
	0xaa, 0xa8, 0x2e, 0xc9, 0x25, 0x41, 0xaa, 0x26, 0xfb, 0xd3, 0x83, 0x5c, 0x46, 0xe4, 0xdc, 0x7c,
	0x2e, 0x17, 0xba, 0x03, 0xb2, 0x63, 0x88, 0xfc, 0x09, 0xee, 0x40, 0x70, 0x57, 0xac, 0x69, 0x34,
	0x40, 0x80, 0xe8, 0x96, 0x0c, 0x6b, 0x35, 0xfd, 0x52, 0xb0, 0xc7, 0xbe, 0x07, 0x72, 0xef, 0xab,
	0x05, 0xe1, 0x19, 0xc4, 0x5d, 0x35, 0xb3, 0x8f, 0x7b, 0x79, 0x93, 0xcf, 0xee, 0xfb, 0x1a, 0x43,
	0xff, 0xb7, 0x6c, 0x80, 0xa7, 0xb0, 0x7d, 0x55, 0x96, 0x32, 0xd2, 0x8f, 0x8b, 0xf1, 0xa1, 0xd7,
	0x1b, 0x15, 0x65, 0x03, 0xbc, 0x84, 0xb8, 0xeb, 0x75, 0x33, 0xbe, 0x2f, 0xfb, 0x0f, 0xe7, 0x2c,
	0x7a, 0x92, 0xdd, 0x3d, 0x47, 0xb2, 0xc8, 0xf3, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x85,
	0xdf, 0xd7, 0xd6, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUserByName(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*User, error)
	AddUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*CommonUserRes, error)
	DelUserByName(ctx context.Context, in *DelUserReq, opts ...grpc.CallOption) (*CommonUserRes, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUserByName(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user.UserService/GetUserByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*CommonUserRes, error) {
	out := new(CommonUserRes)
	err := c.cc.Invoke(ctx, "/user.UserService/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DelUserByName(ctx context.Context, in *DelUserReq, opts ...grpc.CallOption) (*CommonUserRes, error) {
	out := new(CommonUserRes)
	err := c.cc.Invoke(ctx, "/user.UserService/DelUserByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	GetUserByName(context.Context, *GetUserReq) (*User, error)
	AddUser(context.Context, *User) (*CommonUserRes, error)
	DelUserByName(context.Context, *DelUserReq) (*CommonUserRes, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) GetUserByName(ctx context.Context, req *GetUserReq) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByName not implemented")
}
func (*UnimplementedUserServiceServer) AddUser(ctx context.Context, req *User) (*CommonUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (*UnimplementedUserServiceServer) DelUserByName(ctx context.Context, req *DelUserReq) (*CommonUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelUserByName not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUserByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUserByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserByName(ctx, req.(*GetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DelUserByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DelUserByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/DelUserByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DelUserByName(ctx, req.(*DelUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserByName",
			Handler:    _UserService_GetUserByName_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _UserService_AddUser_Handler,
		},
		{
			MethodName: "DelUserByName",
			Handler:    _UserService_DelUserByName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
